spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ramadan877/cloud-config
          default-label: main
server:
  port: 8080
