spring:
  application:
    name: productservice
  cloud:
    config:
      uri: http://configserver:8888
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://registryserver:8761/eureka/
